### ISSUE TITLE
Unable to get document by id returned from /documents

### ISSUE THREAD

**Issue by apetcu** [code4romania/expert-consultation-api#104]
/api/documents returns `metadataId` instead of `id` which causes the endpoint /documents/{id} to throw "Resource not found"

**Comment by RaduCStefanescu** [comment]
I checked the current `develop` branch and the ID returned by the POST `/api/documents` endpoint can be used to return the following information:
GET `/api/documents/{id}` - document metadata
GET `/api/documents/{id}/consolidated` - document structure

**Comment by RaduCStefanescu** [comment]
I will also check the solution running on the Docker container to see of this issue happens on that version

**Comment by paulicit** [comment]
I just got the project and I saw this was not working for me on develop branch. I created a PR with a fix https://github.com/code4romania/expert-consultation-api/pull/108 
Feel free to close it if it's not needed or if I misunderstood the issue.
