### ISSUE TITLE
Set meta charset to utf8 for fields

### ISSUE THREAD

**Issue by apetcu** [code4romania/expert-consultation-api#105]
Meta charset is currently set to `latin1_swedish_ci`. It must be changed to `utf8_general` or something else in order to fit Romanian characters

**Comment by kixx** [comment]
That is the default charset/collation for MySQL 5.x. I'll change the docker compose file to start the mysql container with the proper collation

**Comment by kixx** [comment]
PR request https://github.com/code4romania/expert-consultation-api/pull/107

I guess the same fix should be applied to the corresponding 
 compose file in the client project https://github.com/code4romania/expert-consultation-client/blob/develop/etc/docker/docker-compose-backend.yml

I'll see to it tomorrow.
