### ISSUE TITLE
Diacritics are not supported in DB

### ISSUE THREAD

**Issue by trestianp** [code4romania/expert-consultation-api#109]
When data from a PDF is saved into document_nodes table, diacritics are not saved.

![document_nodes_table](https://user-images.githubusercontent.com/3278514/77237615-629d4680-6bd2-11ea-88a0-08a6e418e7df.PNG)

**Comment by paulicit** [comment]
This could be only on my local machine.
Depends what Collation is set in production. 
The fix for this is to set utf8 collation in mysql by altering table and also add `&characterEncoding=UTF-8` to application.yml file on url connection

**Comment by RaduCStefanescu** [comment]
> This could be only on my local machine.
> Depends what Collation is set in production.
> The fix for this is to set utf8 collation in mysql by altering table and also add `&characterEncoding=UTF-8` to application.yml file on url connection

Hi @trestianp 
Can you please make a pull request to update the `application.yml` file?

**Comment by trestianp** [comment]
Yes, I'll create a PR for this.
