### ISSUE TITLE
[Users] Import a list of users by copy/paste from Excel file

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/expert-consultation-api#11]
As an admin user of the Legal Consultation platform I want to be able to import a list of users by copy pasting from an excel file.

![Adauga membri (2)](https://user-images.githubusercontent.com/15039873/58744598-c7946f80-83f9-11e9-86a1-7a5d4a2925ad.png)

**Comment by ciprianbolocan** [comment]
O sa ma ocup eu de el

**Comment by RaduCStefanescu** [comment]
In progress @ciprianbolocan
