### ISSUE TITLE
Search and filter users

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/expert-consultation-api#120]
We need to have the ability to search users by name and to filter users based on specialisation.

**Comment by cosmingodeanu** [comment]
I'll take this one.

**Comment by cosmingodeanu** [comment]
How is the specialisation specified for users? I see the model has a `district` field, is that it?

**Comment by georgebejan** [comment]
@cosmingodeanu 
We just need an endpoint for filtering users. For now it will take a `searchTerm` and will return users which match that search term (any of the user fields match the term)

**Comment by cosmingodeanu** [comment]
Pull request here: https://github.com/code4romania/expert-consultation-api/pull/140
