### ISSUE TITLE
Use AWS SES to send emails

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/expert-consultation-api#121]
Currently we use SMTP to send emails, but for more reliability we need to switch the email sending to use AWS SES.

**Comment by trestianp** [comment]
I will start working on this.

**Comment by RaduCStefanescu** [comment]
All yours @trestianp

**Comment by trestianp** [comment]
PR opened for this: https://github.com/code4romania/expert-consultation-api/pull/130

For email sender, I added a mock email address that will need to be updated with a real email.

Besides the code implementation, some configuration is required in AWS:
1. Verify the sender (and receiver when in Sandbox mode) email address:
https://docs.aws.amazon.com/ses/latest/DeveloperGuide/verify-email-addresses-procedure.html
2. When going to production: Default SES is in sandbox mode, we need to request production use: https://docs.aws.amazon.com/ses/latest/DeveloperGuide/request-production-access.html
3. Nice to have: Enable Email Feedback Forwarding (Should be enabled by default, just double check) : https://docs.aws.amazon.com/ses/latest/DeveloperGuide/monitor-sending-activity-using-notifications-email.html#monitor-sending-activity-using-notifications-email-enabling
