### ISSUE TITLE
numberOfComments is null for article document node

### ISSUE THREAD

**Issue by aggo** [code4romania/expert-consultation-api#137]
We need to display in the frontend the number of comments of an article node. Right now, this is not returned properly from the backend.
![image](https://user-images.githubusercontent.com/7957519/82729349-757de580-9cff-11ea-887a-7b8e49c95520.png)

**Comment by vgheo** [comment]
Hello. I could give a try at this issue.

**Comment by vgheo** [comment]
In the current model, there is no reference from DocumentNode to Comment.
eg
```
class DocumentNode {
@OneToMany(mappedBy = "documentNode", fetch = FetchType.LAZY)
List<Comment> comments;
}
```

Adding this would greatly simplify the implementation of this issue.
I suppose that other features may use this reference.

Alternatively  - the mapper would query the comments repo to compute list of related Comments for a given DocumentNode.

Please advise on solution.

**Comment by RaduCStefanescu** [comment]
This is the type of situation where I would decouple the DTO representation from the data model one. So, let's return a DTO that gets information from both the DocumentNode and the Comments data model. What do you think?

**Comment by georgebejan** [comment]
> 
> 
> This is the type of situation where I would decouple the DTO representation from the data model one. So, let's return a DTO that gets information from both the DocumentNode and the Comments data model. What do you think?

We already have this in `DocumentNodeDto` - the number of comments is present there. In `DocumentServiceImpl:fetchConsolidatedByMetadataId` we have an example of how the number of comments is computed, but that works only for the root element of the tree. We need the same for every document node

**Comment by RaduCStefanescu** [comment]
Ah, thanks for the info @georgebejan Does it make sense to have the method implemented for the whole document? Do we need to know at anytime the number of comments for the whole document? 
I know I sound like captain Obvious, but let's implement the same logic for a single node as well.
Does this answer your question @vgheo ?

**Comment by vgheo** [comment]
IMO the current implementation is non-cohesive - the full computation of the DTO should be encapsulated in the DocumentNodeDTO (and delegates).

I have submitted a proposal.

A possibly better alternative is, per my previous comment, to add the one-to-many reference DocumentNode#comments.

Would this change be acceptable ?
