### ISSUE TITLE
Allow for more than 255 characters in the text of a comment

### ISSUE THREAD

**Issue by aggo** [code4romania/expert-consultation-api#138]
The text of a comment allows right now the default of 255 characters. Since most likely the comments will be longer than that, migrate this column to allow for more.

**Comment by lzrmihnea** [comment]
@aggo @RaduCStefanescu How many characters? Maximum possible?

**Comment by lzrmihnea** [comment]
> @aggo @RaduCStefanescu How many characters? Maximum possible?

Nevermind, found it.
I'm working on this and will create a PR shortly.

**Comment by aniri** [comment]
closing as it was implemented in #167
