### ISSUE TITLE
[Documents] Consolidate the comments added for a document breakdown unit

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/expert-consultation-api#15]
As an admin of the Legal Consultation platform I want to be able to consolidate the comments received for a legal document.
Consolidating the comments means approving or rejecting the comments.
For approved comments, the comments are reflected in the changes for the text of the document breakdown unit.

![RU - lege - integral - cu comentarii - open](https://user-images.githubusercontent.com/15039873/58744789-3b377c00-83fc-11e9-8ce2-c36ea75c6c9a.png)

**Comment by MihaiTudorP** [comment]
In progress @MihaiTudorP
