### ISSUE TITLE
Failed test on build

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/expert-consultation-api#152]
There are tests failling, please see below:
 
[ERROR]   DocumentControllerIntegrationTest.saveDocument:80->assertThatDocumentNodeTreeIsGeneratedCorrectly:136->assertDocumentNodeContent:220 
Expecting:
  <"Sample document introduction that can be on one line or on multiplelines">
to be equal to:
  <"multiple lines  Sample document introduction that can be on one line or on multiple lines  ">

**Comment by cezarmathe** [comment]
I think I may have found the issue.

```
java.lang.AssertionError: 
Expecting:
  <"Sample document introduction that can be on one line or on multiple lines">
to be equal to:
  <"multiple lines  Sample document introduction that can be on one line or on multiple lines  ">
ignoring whitespace differences
```

The file `test/resources/pdf/sample_legal_document.pdf` contains:

---

**Document title**

**on**

**multiple lines**

Sample document introduction that can be on one line or

on multiple

lines

---
