### ISSUE TITLE
Document versioning design discussion

### ISSUE THREAD

**Issue by georgebejan** [code4romania/expert-consultation-api#169]
The purpose of this issue is to have a discussion about the document versioning system.

### Context and Problem Statement

Each time a document is uploaded to the platform we store it as a `DocumentConsolidated`. This entity has two main parts: `DocumentMetadata` and `DocumentNode`. 
`DocumentMetadata` holds information about about the document (title, initiator, etc).
`DocumentNode` is the result of the document parsing process and represents the root of a tree. Each node in the tree represents a section, chapter, article or paragraph. 

Once the consultation process is started on a document, members of the platform can leave comments for different parts of the document (nodes). Comments are linked with their corresponding `DocumentNode`.At the end of the process, the admin of the document will create a new version based on the comments. This version will be exported and sent back to the initiator.

We want to keep track of these versions: before the consultation and after the consultation. Other versions might appear (e.g the final form published in "Monitorul Oficial"). Also not all versions need to be parsed and represented in the tree structure (e.g the version in "Monitorul Oficial" will be only as a PDF file with the final version - no need to parse it and transform it in the tree structure since no comments are needed to this version)

We need a solution on how to keep all this information about different states of the document.

### Considered option

The straightforward solution would be to have a `DocumentConsolidated` entry for each state of the document and add a new model which keeps track of those entries and a state assigned to each of it.
Pros:
* easy to implement
* can scale to any number of states easily
* each state has it's on comments since we work on different `DocumentNode` tree for each state
Cons:
* not really suitable for states where we don't need to parse the document, but only to store it

This is an open discussion and any ideas are welcome!

**Comment by sfynxu** [comment]
Hi! There are several standards to document lifecycle! One solution is to use database for defining some states, and transitions between the states. In this way you may select and update the workflows and create some statistics.

**Comment by lzrmihnea** [comment]
For one, a Comment should be linked to a DocumentNode and the Version of the Document, for historical reasons. Would this make sense?

To easily see the difference between states, there were some framework which could solve this issue out of the box, but I have to research that.

**Comment by sfynxu** [comment]
I'd rather link comment to transition. Thos is in order to document the change and  I would optate to mandatory!
