### ISSUE TITLE
[Documents] Track changes in consolidated document based on comments

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/expert-consultation-api#17]
As an admin user I want to be able to modify the content of the original document based on the comments added by the users.

When approving a comment added to a document breakdown unit, the result needs to be a change in the original document. The change on the original document must be linked to the approved comment.

![RU - lege - integral - cu comentarii - open (1)](https://user-images.githubusercontent.com/15039873/58751725-4ff52d80-8457-11e9-98de-d18f9f74e708.png)

**Comment by damianr13** [comment]
I will take this

**Comment by RaduCStefanescu** [comment]
Based on what we decided in the UX and workflow, this issue is not needed anymore.
