### ISSUE TITLE
Add specialization field to user

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/expert-consultation-api#180]
When creating a new user, a specialization field should be added to the user info.

**Comment by aniri** [comment]
@RaduCStefanescu how will these specializations be stored? will they be in a predefined list and shown as a dropdown to the user? or are they any text input?

**Comment by RaduCStefanescu** [comment]
@aniri the specializations will be stored as an enumeration and the frontend will display them as a dropdown.
I will come back with a list of specializations we can use.

**Comment by georgebejan** [comment]
@RaduCStefanescu  Maybe we can do it like tags: allow any text and show matches as the user types and create new specialization if not found

**Comment by RaduCStefanescu** [comment]
@georgebejan sounds good, because we will have a lot of specialization as the platform grows.

**Comment by aniri** [comment]
@RaduCStefanescu @georgebejan maybe we could add a separate task for handling the list of specializations? either as an enum or text matching :D

**Comment by RaduCStefanescu** [comment]
> @RaduCStefanescu @georgebejan maybe we could add a separate task for handling the list of specializations? either as an enum or text matching :D

Hmm, why not keep it in the same task? They are linked anyway.

**Comment by lucianbc** [comment]
I guess this one is closed by [this PR](https://github.com/code4romania/expert-consultation-api/pull/189)
