### ISSUE TITLE
Extend Document Type enumeration

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/expert-consultation-api#183]
Currently, we have in the document type enumeration the following values - LEGE, HG, ORDONANTA.
We should extend this enumeration by adding the values - REGULAMENT, REGULAMENT-CADRU, HOTARARE, HOTARARE CONSILIU NATIONAL.

**Comment by Daniel194** [comment]
Work in progress - @Daniel194

**Comment by RaduCStefanescu** [comment]
All yours @Daniel194

**Comment by RaduCStefanescu** [comment]
Fixed in #186
