### ISSUE TITLE
Add comment replies to number of comments

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/expert-consultation-api#184]
Currently, when we display the number of comments in the frontend, we only account for the comments and not the comment replies. We should also consider the comment replies when returning the number of comments from the backend.

**Comment by Daniel194** [comment]
Work in progress

**Comment by RaduCStefanescu** [comment]
All yours @Daniel194

**Comment by RaduCStefanescu** [comment]
Fixed in #188
