### ISSUE TITLE
Incorrect link sent in new document email

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/expert-consultation-api#194]
When sending a new document assigned email, the link is incorrect.

What we send: https://staging.legiinlucru.ro/api/documents//054e26ca-dac1-4ba9-a13e-09e4b77d7733
The correct link: https://staging.legiinlucru.ro/documents//054e26ca-dac1-4ba9-a13e-09e4b77d7733

Hint: it contains an extra `/api`

**Comment by vidi42** [comment]
Am deschis un PR pentru issue-ul acesta

**Comment by RaduCStefanescu** [comment]
Nice @vidi42 
Am facut merge la modificari.
