### ISSUE TITLE
Assign entire document to one ore more users in the platform

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/expert-consultation-api#3]
As an admin of the Legal Consultation platform I want to be able to assign a document to a user in the platform.
We need to create a new entity that will contain the relationship between the document and the user. A user that has been added to a document will be able to post comments on that document. Every user will be able to view the documents in the platform. 

![Adauga membri](https://user-images.githubusercontent.com/15039873/58744312-dc6f0400-83f5-11e9-80d1-a74049f75f3d.png)

**Comment by Andu033** [comment]
I can work on that.

**Comment by RaduCStefanescu** [comment]
In progress @Andu033

**Comment by RaduCStefanescu** [comment]
Hi @Andu033 
How is it going with the development, need any help?

**Comment by Andu033** [comment]
No. It's ok. I had little time lately but I will finish that tomorrow at hackday. Sorry for being late.

**Comment by RaduCStefanescu** [comment]
Closed in #113
