### ISSUE TITLE
Edit the contents of the breakdown document

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/expert-consultation-api#4]
As an admin of the Legal Consultation platform, I want to be able to edit the contents of a breakdown document.

After loading the document in the platform, the automatic process of breaking down the document into units takes place. The process might not work as intended, so the user must be able to edit the contents of the document.
CRUD operations need to be implemented for a `document node`

**Comment by RaduCStefanescu** [comment]
In progress @RaduCStefanescu

**Comment by RaduCStefanescu** [comment]
Due to time constraints, I am unable to implement this issue
Moving it back to `To Do`

**Comment by Daniel194** [comment]
I'd like to work on this task :)

**Comment by lucianoprea** [comment]
Hi, I want to give a try to this issue. 
In progress @lucianoprea

**Comment by RaduCStefanescu** [comment]
@lucianoprea thank you for picking up this issue
Will you be making a PR?
If we can help with any question, please let me know

**Comment by lucianoprea** [comment]
@RaduCStefanescu yes, I want to make a PR. I'll get in touch with you or George if I need more details/clarification. Thx

**Comment by GhenadieCebanu** [comment]
looking into
