### ISSUE TITLE
[Document processing] Implement loading of pdf files

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/expert-consultation-api#46]
As part of the loading of files in the platform, a service to load and read pdf file contents needs to be developer.

The service should be using a Java PDF library like https://pdfbox.apache.org/

The service should be able to receive the path to a PDF file and return the contents of the file.

**Comment by georgebejan** [comment]
in progress @georgebejan

**Comment by RaduCStefanescu** [comment]
Issue handled in #63
