### ISSUE TITLE
[Document processing] Implement parsing of generic pdf file

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/expert-consultation-api#47]
As a legal consultation user, I want to be able to load a pdf file in a predefined format and break the content of the file in chapters and articles.

The pdf file will have a predefined format, an example file can be provided by request.
A strategy needs to be implemented to break the content of the file in the desired format: chapters and articles.

**Comment by georgebejan** [comment]
in progress @georgebejan

**Comment by RaduCStefanescu** [comment]
Issue has been tested on latest build.
