### ISSUE TITLE
[Infrastructure] Automatic deployment on AWS

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/expert-consultation-api#52]
As part of easy deployment for the application, we need to implement automatic deployment of the docker image containing the project and it's dependencies on a AWS machine. As an automatic deployment provider we will be using Travis-CI.

**Comment by mihairinzis** [comment]
in progress @mihairinzis

**Comment by RaduCStefanescu** [comment]
This issue is fixed in #60
