### ISSUE TITLE
[Documents] Implement voting feature for document comments

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/expert-consultation-api#66]
As a user of the Expert Consultation platform I want to be able to cast votes for comments that are added for a node.

There are a few rules that need to be taken into consideration:
- we implement up-votes and down-votes
- each user has at most 1 up-vote or 1 down-vote per comment
- the voting is anonymous, the platform will not register what votes a user has casted
- an admin can open and close the voting period for a document

**Comment by correndonomundo** [comment]
I'd like to work on this task.

**Comment by BiancaIrimescu3Pillar** [comment]
I'd like also to work on this task:)

**Comment by correndonomundo** [comment]
droppin' out for now

**Comment by correndonomundo** [comment]
droppin' out for now

**Comment by pavelnc** [comment]
I ll take this task

**Comment by RaduCStefanescu** [comment]
Hi @pavelnc !
How is it working with this issue? Anything we can help with?

**Comment by pavelnc** [comment]
Am nevoie de o infromatie legata perioada in care se poate face votarea.
Votarea comenturilor se poate face cand perioada este deschisa din punct de vedere temporar sau este doar un boolean pe care admin ul il seteaza ca fiind true/false.    Pe marți, 10 decembrie 2019, 17:59:58 EET, Radu Stefanescu <notifications@github.com> a scris:  
 
 
Hi @pavelnc !
How is it working with this issue? Anything we can help with?

**Comment by RaduCStefanescu** [comment]
> Am nevoie de o infromatie legata perioada in care se poate face votarea. Votarea comenturilor se poate face cand perioada este deschisa din punct de vedere temporar sau este doar un boolean pe care admin ul il seteaza ca fiind true/false. Pe marți, 10 decembrie 2019, 17:59:58 EET, Radu Stefanescu <notifications@github.com> a scris: Hi @pavelnc ! How is it working with this issue? Anything we can help with? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Hi @pavelnc !
We don't want to have a pre-configured period of time where we have open voting. The way I see it, let's keep a simple boolean configuration that maintains if the voting is open/closed.

I will open a new issue for defining the configuration. It should not be part of this issue.

**Comment by themeshter** [comment]
hey @pavelnc @RaduCStefanescu - wasn't sure what the state was for this issue... Rather than asking I just implemented a naive version of the service (repository, service, mock test following the already existing architectural conventions) and pushed into https://github.com/rnd-forks/expert-consultation-api. 

Planning to add the controller layer these days. Let me know if this is redundant (or even useless) work.

**Comment by RaduCStefanescu** [comment]
Hey @themeshter ! Thank you very much for your contribution, highly welcomed and appreciated.
I will have a look at the implementation in the coming days and get back to you with feedback.
To make it easier for the reviewers, would you be so kind to open a Pull Request and mark it as Work In Progress?
Thank you!

**Comment by themeshter** [comment]
@RaduCStefanescu , just created the pull request. Hopefully I did it the right way :thinking: ...

**Comment by lzrmihnea** [comment]
Based on @themeshter 's work, I've created an updated PR: https://github.com/code4romania/expert-consultation-api/pull/115/files

**Comment by lzrmihnea** [comment]
@RaduCStefanescu  can this be set to `closed` ? 
The last bulletpoint `an admin can open and close the voting period for a document` has not been addressed.
