### ISSUE TITLE
[Documents] Document structure incomplete

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/expert-consultation-api#83]
After saving a new document, if a user wants to see the contents of the document, it is not possible at the moment.

The `GET api/document/{id}/consolidated` returns only the top level node, and not the whole structure.

We need the entire structure of the document to be able to correctly display it in frontend.

**Comment by codrin23** [comment]
Work in progress

**Comment by RaduCStefanescu** [comment]
Tested on latest build.
