### ISSUE TITLE
[Documents] Simplify Comment DTO

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/expert-consultation-api#86]
We need to simplify the comment DTO, as it contains redundant information.
Currently the format of the DTO is:
```
{
    "id": "42e10e2c-db4c-4ce8-8278-320b9ec05034",
    "text": "Un comment adaugat de test!",
    "lastEditDateTime": "2019-12-10T12:11:40.653+0000"
}
```
We just need to supply the text, because the id is part of the URL and edit time should be set by the server.

**Comment by AndraVasilache** [comment]
I'd like to work on this task.

**Comment by RaduCStefanescu** [comment]
Tested on latest build.
