### ISSUE TITLE
[Tests] Random error on MailServiceTest

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/expert-consultation-api#89]
We have random fails on the test:
`MailServiceTest.sendRegisterMail()`

The error happens on this line:
`assertThat(modelCaptor.getValue().get("username")).isEqualTo(user.getFirstName() + ' ' + user.getLastName());`

**Comment by vijayakumarbathini** [comment]
will be working on this issue

**Comment by vijayakumarbathini** [comment]
Seeing Null Pointer Exception when above test case is running but doesn't see test cases are failing. 

I have ran mvn clean install multiple times, but saw all 66 test cases are passing

**Comment by mihairinzis** [comment]
unfortunately it fails relatively often on the ci build. maybe we should simply hard-code the first name and last name of the test user in order to avoid this annoyance in the future..
