### ISSUE TITLE
Create seed database script with test users and documents

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/expert-consultation-api#94]
For testing purposes we need to have a seed script, that adds information to the database in order to run and test the solution.

The seed script needs to save information about users and documents.

**Comment by paulicit** [comment]
I can pick this.
How many users and documents should be created ?
Is an SQL script that we can run manually in a DB Client what you had in mind ?

**Comment by RaduCStefanescu** [comment]
@trestianp are you still up for this issue?
My idea was that it would be awesome to be able to create an admin user and a regular application user, and also be able to create a document structure with comments so that we can test the frontend.
I think a good solution would be to use https://flywaydb.org/

**Comment by trestianp** [comment]
@RaduCStefanescu sure, you can assign this to me. 
I will start by adding one or two records for each table and I can update with more data based on comments on the PR.
