### ISSUE TITLE
Reply to comments feature

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/expert-consultation-api#95]
Currently, comments can be added to any element of the document node structure.

One of the features of the platform is that we need to be able to support replies to comments.
A reply needs to be defined as a new datamodel, and it needs to contain at least the following information:
- an id
- the id of the comment that it replies to
- the id of the user that posted the reply
- the text message of the reply 
- the date and time of the reply

The replies feature needs to implement CRUD operations and the following elements
- a controller
- a service
- a repository
- a model

**Comment by Daniel194** [comment]
I'm working on this :)

**Comment by RaduCStefanescu** [comment]
In progress @Daniel194

**Comment by RaduCStefanescu** [comment]
Fixed in #101
